export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const OPEN_PROFILE_POPOVER = "OPEN_PROFILE_POPOVER";
export const CLOSE_PROFILE_POPOVER = "CLOSE_PROFILE_POPOVER";
export const OPEN_MESSAGE_POPOVER = "OPEN_MESSAGE_POPOVER";
export const CLOSE_MESSAGE_POPOVER = "CLOSE_MESSAGE_POPOVER";
